---
version: v2.12.1

name: golangci-lint
destination: .

plugins:
  - module: fillmore-labs.com/zerolint
    import: fillmore-labs.com/zerolint/gclplugin
    path: .
  - module: fillmore-labs.com/scopeguard
    import: fillmore-labs.com/scopeguard/gclplugin
    version: v0.0.7
  - module: fillmore-labs.com/errortype
    import: fillmore-labs.com/errortype/gclplugin
    version: v0.0.11
