---
no-hard-tabs:
  ignore_code_languages:
    - go
  spaces_per_tab: 4
line-length:
  line_length: 120
  code_blocks: false
  tables: false
ol-prefix:
  style: ordered
no-blanks-blockquote:
  enabled: false
no-inline-html:
  allowed_elements: ["b", "code", "details", "summary", "p"]
