---
# yaml-language-server: $schema=https://json.schemastore.org/prettierrc.json
printWidth: 120
proseWrap: always
tabWidth: 4
useTabs: false
overrides:
  - files: "*.md"
    options:
      tabWidth: 2
  - files: "*.yaml"
    options:
      tabWidth: 2
  - files: "*.yml"
    options:
      tabWidth: 2
