// Code generated by "stringer -linecomment -type category"; DO NOT EDIT.

package visitor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[catNone-0]
	_ = x[catAddress-1]
	_ = x[catArgumentNil-2]
	_ = x[catCast-3]
	_ = x[catCastNil-4]
	_ = x[catComparison-5]
	_ = x[catComparisonError-6]
	_ = x[catComparisonInterface-7]
	_ = x[catDeref-8]
	_ = x[catError-9]
	_ = x[catMethodExpression-10]
	_ = x[catNew-11]
	_ = x[catParameter-12]
	_ = x[catReceiver-13]
	_ = x[catResult-14]
	_ = x[catReturnNil-15]
	_ = x[catStarType-16]
	_ = x[catStructEmbedded-17]
	_ = x[catStructField-18]
	_ = x[catTypeAssert-19]
	_ = x[catTypeDeclaration-20]
	_ = x[catVar-21]
}

const _category_name = "unkaddargcstnilcmpcmecmidererrmexnewparrcvresrettypembfldartdclvar"

var _category_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66}

func (i category) String() string {
	if i < 0 || i >= category(len(_category_index)-1) {
		return "category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _category_name[_category_index[i]:_category_index[i+1]]
}
