// Code generated by "stringer -linecomment -type category"; DO NOT EDIT.

package visitor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[catNone-0]
	_ = x[catAddress-1]
	_ = x[catCast-2]
	_ = x[catComparison-3]
	_ = x[catDeref-4]
	_ = x[catError-5]
	_ = x[catInterfaceComparison-6]
	_ = x[catMethodExpression-7]
	_ = x[catNew-8]
	_ = x[catNilParameter-9]
	_ = x[catNilReturn-10]
	_ = x[catParameter-11]
	_ = x[catReceiver-12]
	_ = x[catResult-13]
	_ = x[catStarType-14]
	_ = x[catStructEmbedded-15]
	_ = x[catStructField-16]
	_ = x[catTypeAssert-17]
	_ = x[catTypeDeclaration-18]
	_ = x[catVar-19]
}

const _category_name = "unkaddcstcmpdererrcmimexnewparretargrcvrestypembfldartdclvar"

var _category_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60}

func (i category) String() string {
	if i < 0 || i >= category(len(_category_index)-1) {
		return "category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _category_name[_category_index[i]:_category_index[i+1]]
}
