---
name: Test
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Go ${{ matrix.go }}
    permissions:
      checks: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    strategy:
      matrix:
        go: ["1.25", "1.24"]
        include:
          - go: "1.25"
            go-version: "1.25.4"
            latest: true
          - go: "1.24"
            go-version: "1.24.10"
    env:
      GOTOOLCHAIN: local
    steps:
      - name: ✔ Check out
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
        with:
          persist-credentials: false
      - name: 🐹 Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"
      - name: 📠 Go Telemetry
        run: go telemetry on
      - name: 🧸 golangci-lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601  # v9.1.0
        if: ${{ matrix.latest }}
        with:
          version: v2.6.2
          verify: false
      - name: 🔨 Test
        run: |
          (cd ./pkg/internal/analyzer/testdata && go mod download)
          go test -coverprofile=cover.out ./...
      - name: 🧑🏻‍💻 codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
        if: ${{ matrix.latest }}
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: fillmore-labs/zerolint
      - name: 🛜 Dependencies
        uses: actions/go-dependency-submission@f35d5c9af13ce9cc32f7930b171e315e878f6921  # v2.0.3
        if: ${{ matrix.latest }}
        with:
          go-mod-path: go.mod
          go-build-target: .
