---
name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Go ${{ matrix.go }}
    permissions:
      checks: write
      contents: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go: ["1.24", "1.23"]
        include:
          - go: "1.24"
            go-version: "1.24.0"
            update-coverage: true
          - go: "1.23"
            go-version: "1.23.6"
    env:
      GOTOOLCHAIN: local
    steps:
      - name: ✔ Check out
        uses: actions/checkout@v4
      - name: 🐹 Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: 🧸 golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
      - name: 🔨 Test
        run: |
          (cd ./pkg/internal/visitor/testdata && go mod download)
          go test -coverprofile=cover.out ./...
        env:
          GOEXPERIMENT: aliastypeparams
      - name: 🧑🏻‍💻 codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.update-coverage }}
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
