---
name: Test
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Go ${{ matrix.go }}
    permissions:
      checks: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    strategy:
      matrix:
        go: ["1.26", "1.25", "1.24"]
        include:
          - go: "1.26"
            go-version: "1.26.0-rc.1"
          - go: "1.25"
            go-version: "1.25.5"
            latest: true
          - go: "1.24"
            go-version: "1.24.11"
    env:
      GOTOOLCHAIN: local
    steps:
      - name: ✔ Check out
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false
      - name: 🐹 Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "**/go.sum"
      - name: 📠 Go Telemetry
        run: go telemetry on
      - name: 🧸 golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # v9.2.0
        if: ${{ matrix.latest }}
        with:
          version: v2.7.2
          verify: false
      - name: 🔨 Test
        run: |
          (cd ./pkg/internal/analyzer/testdata && go mod download)
          go test -coverprofile=cover.out ./...
      - name: 🧑🏻‍💻 codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de  # v5.5.2
        if: ${{ matrix.latest }}
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: fillmore-labs/zerolint
      - name: 🛜 Dependencies
        uses: actions/go-dependency-submission@f35d5c9af13ce9cc32f7930b171e315e878f6921  # v2.0.3
        if: ${{ matrix.latest }}
        with:
          go-mod-path: go.mod
          go-build-target: .
